/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "eu-west-2",
  aws_cognito_identity_pool_id:
    "eu-west-2:305ec9e0-9e29-428f-a900-fb7d599d0b71",
  aws_cognito_region: "eu-west-2",
  aws_user_pools_id: "eu-west-2_TsrFRqqhk",
  aws_user_pools_web_client_id: "jjl3jb2jl6ek5u5g1i13kk6n9",
  oauth: {},
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_user_files_s3_bucket:
    "karimlandwebsite523f9d2840804269b44400814cd464b200112-prod",
  aws_user_files_s3_bucket_region: "eu-west-2",
  aws_sdk_load_config: 1,
  aws_appsync_graphqlEndpoint:
    "https://hcn2ijtspbdfrhlz5u2pkeeezm.appsync-api.eu-west-2.amazonaws.com/graphql",
  aws_appsync_region: "eu-west-2",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_appsync_apiKey: "da2-vn5yd7brtrhpfjra2ym7hlmw3u",
  aws_cognito_login_mechanism: ["PREFERRED_USERNAME"],
}

export default awsmobile
