/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:a7a2a15e-87a5-4e35-837a-54e3cc4d22e5",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_xds0Glm5A",
    "aws_user_pools_web_client_id": "2u3gs3gcven0it5len31v81rkp",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "karimlandwebapp2e16e782de77449c9da770d45c1c93ee130635-prod",
    "aws_user_files_s3_bucket_region": "eu-west-2",
    "aws_user_files_s3_dangerously_connect_to_http_endpoint_for_testing": true,
    "aws_appsync_graphqlEndpoint": "https://fetdvfvnqfd3fjdfcqyhf64fia.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-xzc77bkthffcneokqnvek7wqmu",
    "aws_appsync_dangerously_connect_to_http_endpoint_for_testing": true
};


export default awsmobile;
